name: Simwatch

on:
  push:
    branches:
      - master
      - gh-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: go modules cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: build
        run: go build -o simwatch-server cmd/simwatch/main.go
      - name: store binary
        uses: actions/upload-artifact@v3
        with:
          name: simwatch-server
          path: simwatch-server
      - name: debug env
        run: echo "${{ github.event }}"
      - name: webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: http://aquavitale.ru:5000/receiver
          webhook_secret: surviv0r
          webhook_type: json
          data: '{ "payload": "$github" }'
