name: Simwatch

on:
  push:
    branches:
      - master
      - gh-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: build
        run: go build -o simwatch-server cmd/simwatch/main.go
